
== `bit.hpp`

https://github.com/intel/cpp-std-extensions/blob/main/include/stdx/bit.hpp[`bit.hpp`]
provides an implementation that mirrors
https://en.cppreference.com/w/cpp/header/bit[`<bit>`], but is
`constexpr` in C++17. It is mostly based on intrinsics.

=== `bit_mask`

`bit_mask` is a function for constructing a bit mask between most-significant
and least-significant bits.

[source,cpp]
----
constexpr auto x = stdx::bit_mask<std::uint8_t, 5, 3>();
static_assert(x == std::uint8_t{0b0011'1000});

// Lsb may be omitted (meaning it's 0)
constexpr auto y = stdx::bit_mask<std::uint8_t, 5>();
static_assert(y == std::uint8_t{0b0011'1111});

// omitting both Msb and Lsb means the entire range of the type
constexpr auto z = stdx::bit_mask<std::uint8_t>();
static_assert(z == std::uint8_t{0b1111'1111});
----

`Msb` and `Lsb` denote a closed (inclusive) range where `Msb >= Lsb`. The first
template argument must be an unsigned integral type or a `std::array` of
unsigned integral types. In the case of an array, the elements are considered to
be in order least significant to most significant.

[source,cpp]
----
constexpr auto x = stdx::bit_mask<std::array<std::uint8_t, 3>, 19>>();
// x == { 0xff, 0xff, 0x0f }
----

`bit_mask` is also available for use with "normal" value arguments rather than
template arguments:

[source,cpp]
----
constexpr auto x = stdx::bit_mask<std::uint8_t>(5, 3);
static_assert(x == std::uint8_t{0b0011'1000});

// Lsb may be omitted (meaning it's 0)
constexpr auto y = stdx::bit_mask<std::uint8_t>(5);
static_assert(y == std::uint8_t{0b0011'1111});
----

=== `bit_pack`

`bit_pack` is a function for packing multiple unsigned integral values into a
larger bit width value.

[source,cpp]
----
constexpr auto x = stdx::bit_pack<std::uint32_t>(0x12, 0x34, 0x56, 0x78);
static_assert(x == 0x1234'5678);
constexpr auto y = stdx::bit_pack<std::uint32_t>(0x1234, 0x5678);
static_assert(y == x);
----

`bit_pack` can be used:

- to pack 2 `std::uint8_t`​s into a `std::uint16_t`
- to pack 2 `std::uint16_t`​s into a `std::uint32_t`
- to pack 2 `std::uint32_t`​s into a `std::uint64_t`
- to pack 4 `std::uint8_t`​s into a `std::uint32_t`
- to pack 4 `std::uint16_t`​s into a `std::uint64_t`
- to pack 8 `std::uint8_t`​s into a `std::uint64_t`

The arguments are listed in order of significance, i.e. for the binary
overloads, the first argument is the high bits, and the second argument the low
bits.

=== `bit_size`

`bit_size` returns a `std::size_t`: the size of its type argument in bits. For
unsigned integral types, this is equivalent to
https://en.cppreference.com/w/cpp/types/numeric_limits/digits[`std::numeric_limits<T>::digits`].

[source,cpp]
----
constexpr std::size_t x = stdx::bit_size<std::uint8_t>();
static_assert(x == 8);
----

=== `bit_unpack`

`bit_unpack` is a function for unpacking an unsigned integral values into multiple
smaller bit width values.

[source,cpp]
----
auto const [a, b] = stdx::bit_unpack<std::uint16_t>(0x1234'5678u);
assert(a == 0x1234u);
assert(b == 0x5678u);
----

`bit_unpack` can be used:

- to unpack a `std::uint16_t`  into 2 `std::uint8_t`​s
- to unpack a `std::uint32_t`  into 2 `std::uint16_t`​s
- to unpack a `std::uint32_t`  into 4 `std::uint8_t`​s
- to unpack a `std::uint64_t`  into 2 `std::uint32_t`​s
- to unpack a `std::uint64_t`  into 4 `std::uint16_t`​s
- to unpack a `std::uint64_t`  into 8 `std::uint8_t`​s

The return value of `bit_unpack` is actually a `std::array` with elements in
order of significance. In this way `bit_unpack` followed by `bit_pack` produces
the original value.

[source,cpp]
----
constexpr auto a = stdx::bit_unpack<std::uint16_t>(0x1234'5678u);
static_assert(stdx::bit_pack<std::uint32_t>(a[0], a[1]) == 0x1234'5678u);
----

=== `smallest_uint`

`smallest_uint` is a function template that selects the smallest unsigned
integral type that will fit a compile-time value.

[source,cpp]
----
constexpr auto x = stdx::smallest_uint<42>();   // std::uint8_t{}
constexpr auto y = stdx::smallest_uint<1337>(); // std::uint16_t{}

// smallest_uint_t is the type of a call to smallest_uint
using T = stdx::smallest_uint_t<1337>; // std::uint16_t
----

=== `to_be`, `from_be`, `to_le`, `from_le`

`to_be` and `from_be` are variations on `byteswap` that do the job of
https://linux.die.net/man/3/htonl[`htonl` and friends]. On a big-endian machine,
they do nothing, and on a little-endian machine, they are the equivalent of
`byteswap`.

`to_le` and `from_le` do the same thing for little-endian order.

[source,cpp]
----
constexpr auto addr = std::uint32_t{0x7f'00'00'01}; // localhost
packet.dest_addr = stdx::to_be(addr);
----

These functions are defined for unsigned integral types. Of course for
`std::uint8_t` they do nothing.

NOTE: The implementations of `to_be` and `from_be` are identical on a machine
with given endianness (either a no-op, or a byteswap). However they are provided
for clarity of intent.

CAUTION: `from_be` is not the same as `to_le`! (And _vice versa_.) These functions are named from
the point of view of the serialization format. Either we are serializing to/from
big-endian, or to/from little-endian.
