
== `bit.hpp`

https://github.com/intel/cpp-std-extensions/blob/main/include/stdx/bit.hpp[`bit.hpp`]
provides an implementation that mirrors
https://en.cppreference.com/w/cpp/header/bit[`<bit>`], but is
`constexpr` in C++17. It is mostly based on intrinsics.

=== `bit_mask`

`bit_mask` is a function for constructing a bit mask between most-significant
and least-significant bits.

[source,cpp]
----
constexpr auto x = stdx::bit_mask<std::uint8_t, 5, 3>();
static_assert(x == std::uint8_t{0b0011'1000});

// Lsb may be omitted (meaning it's 0)
constexpr auto y = stdx::bit_mask<std::uint8_t, 5>();
static_assert(y == std::uint8_t{0b0011'1111});

// omitting both Msb and Lsb means the entire range of the type
constexpr auto z = stdx::bit_mask<std::uint8_t>();
static_assert(z == std::uint8_t{0b1111'1111});
----

`Msb` and `Lsb` denote a closed (inclusive) range where `Msb >= Lsb`. The first
template argument must be an unsigned integral type.

`bit_mask` is also available for use with "normal" value arguments rather than
template arguments:

[source,cpp]
----
constexpr auto x = stdx::bit_mask<std::uint8_t>(5, 3);
static_assert(x == std::uint8_t{0b0011'1000});

// Lsb may be omitted (meaning it's 0)
constexpr auto y = stdx::bit_mask<std::uint8_t>(5);
static_assert(y == std::uint8_t{0b0011'1111});
----

=== `bit_pack`

`bit_pack` is a function for packing multiple unsigned integral values into a
larger bit width value.

[source,cpp]
----
constexpr auto x = stdx::bit_pack<std::uint32_t>(0x12, 0x34, 0x56, 0x78);
static_assert(x == 0x1234'5678);
constexpr auto y = stdx::bit_pack<std::uint32_t>(0x1234, 0x5678);
static_assert(y == x);
----

`bit_pack` can be used:

- to pack 2 `std::uint8_t`​s into a `std::uint16_t`
- to pack 2 `std::uint16_t`​s into a `std::uint32_t`
- to pack 2 `std::uint32_t`​s into a `std::uint64_t`
- to pack 4 `std::uint8_t`​s into a `std::uint32_t`
- to pack 4 `std::uint16_t`​s into a `std::uint64_t`
- to pack 8 `std::uint8_t`​s into a `std::uint64_t`

The arguments are listed in order of significance, i.e. for the binary
overloads, the first argument is the high bits, and the second argument the low
bits.

=== `bit_size`

`bit_size` returns a `std::size_t`: the size of its type argument in bits. For
unsigned integral types, this is equivalent to
https://en.cppreference.com/w/cpp/types/numeric_limits/digits[`std::numeric_limits<T>::digits`].

[source,cpp]
----
constexpr std::size_t x = stdx::bit_size<std::uint8_t>();
static_assert(x == 8);
----

=== `smallest_uint`

`smallest_uint` is a function template that selects the smallest unsigned
integral type that will fit a compile-time value.

[source,cpp]
----
constexpr auto x = stdx::smallest_uint<42>();   // std::uint8_t{}
constexpr auto y = stdx::smallest_uint<1337>(); // std::uint16_t{}

// smallest_uint_t is the type of a call to smallest_uint
using T = stdx::smallest_uint_t<1337>; // std::uint16_t
----

=== `to_le` and `to_be`

`to_le` and `to_be` are variations on `byteswap` that convert unsigned integral
types to little- or big-endian respectively. On a little-endian machine, `to_le`
does nothing, and `to_be` is the equivalent of `byteswap`. On a big endian
machine it is the other way around.

[source,cpp]
----
constexpr auto x = std::uint32_t{0x12'34'56'78};
constexpr auto y = stdx::to_be(x); // 0x78'56'34'12 (on a little-endian machine)
----

`to_le` and `to_be` are defined for unsigned integral types. Of course for
`std::uint8_t` they do nothing.
