
== `concepts.hpp`

https://github.com/intel/cpp-std-extensions/blob/main/include/stdx/concepts.hpp[`concepts.hpp`]
implements various https://en.cppreference.com/w/cpp/concepts[standard concepts]. In C++17 they are surfaced as compile-time
boolean values.

* https://en.cppreference.com/w/cpp/concepts/same_as[`same_as`]
* https://en.cppreference.com/w/cpp/concepts/derived_from[`derived_from`]
* https://en.cppreference.com/w/cpp/concepts/convertible_to[`convertible_to`]
* https://en.cppreference.com/w/cpp/concepts/integral[`integral`]
* https://en.cppreference.com/w/cpp/concepts/signed_integral[`signed_integral`]
* https://en.cppreference.com/w/cpp/concepts/unsigned_integral[`unsigned_integral`]
* https://en.cppreference.com/w/cpp/concepts/floating_point[`floating_point`]
* https://en.cppreference.com/w/cpp/concepts/equality_comparable[`equality_comparable`]
* https://en.cppreference.com/w/cpp/concepts/totally_ordered[`totally_ordered`]
* https://en.cppreference.com/w/cpp/concepts/invocable[`invocable`]
* https://en.cppreference.com/w/cpp/concepts/predicate[`predicate`]
* https://en.cppreference.com/w/cpp/ranges/range[`range`]

NOTE: For compatibility with the standard and with
https://en.cppreference.com/w/cpp/types/is_base_of[`std::is_base_of`], a class
is considered to be `derived_from` itself.

NOTE: `range` is in the `stdx` namespace, and is defined in terms of
`std::begin` and `std::end`, unlike the standard which has `std::ranges::range`
defined in terms of `std::ranges::begin` and `std::ranges::end`.

`concepts.hpp` also has a couple of non-standard but useful concepts.

=== `callable`

`callable` is modelled by functions by and objects with `operator()`. In
particular it is true for generic lambda expressions, where `operator()` is a
function template.

[source,cpp]
----
auto f() -> void {}
static_assert(stdx::callable<decltype(f)>);

auto lambda = [] (int i) { return i + 1; };
static_assert(stdx::callable<decltype(lambda)>);

auto generic_lambda = [] (auto i) { return i + 1; };
static_assert(stdx::callable<decltype(generic_lambda)>);
----

=== `has_trait`

`has_trait` is used to turn a type trait (standard or otherwise) into a concept.
There are many type traits and comparatively few standard concepts; this concept
helps bridge the gap more easily and concisely than writing out boilerplate
concepts for type traits.

[source,cpp]
----
template <stdx::has_trait<std::is_class> T>
auto f(T) -> void {
  // can only be called with class types
}
----

For the purposes of `has_trait`, a type trait is a class template with one
parameter that has a `constexpr static bool value` member.

=== `same_as_unqualified`

`same_as_unqualified` is true when two types are the same are removing top-level
cv-qualifications and references, if any. It's useful for constraining hidden
friends -- particularly when member functions would need to be replicated with
different reference qualifiers before C++23.

[source,cpp]
----
struct S {
  // before C++20
  auto f() & { /* ... */ }
  auto f() const & { /* ... */ }
  auto f() && { /* ... */ }
  auto f() const && { /* ... */ }
  // (and 4 more for volatile qualifiers!)

  // with C++23's explicit object parameter ("deducing this")
  template <typename Self>
  auto f(this Self&& s) {
    // Self is perfectly-forwarded
  }

private:
  // hidden friend alternative
  template <same_as_unqualified<S> Self>
  friend auto f(Self&& s) {
    // Self is perfectly-forwarded
  }
};
----
