
== `ct_format.hpp`

https://github.com/intel/cpp-std-extensions/blob/main/include/stdx/ct_format.hpp[`ct_format.hpp`]
provides `ct_format`, a compile-time function for formatting strings.

NOTE: Like xref:ct_string.adoc#_ct_string_hpp[`ct_string`], `ct_format` is
available only in C++20 and later.

The format string is provided as a template argument, and the arguments to be
formatted as regular function arguments.

The result type is a `stdx::format_result` containing two members: the
xref:ct_string.adoc#_ct_string_hpp[`ct_string`] (wrapped in a `cts_t`) and a
xref:tuple.adoc#_tuple_hpp[`tuple`] of the format arguments.
[source,cpp]
----
auto s = stdx::ct_format<"Hello {} {}">(42, 17);
// s is stdx::format_result{"Hello {} {}"_ctst, stdx::tuple{42, 17}}
----

When format arguments are available at compile-time, wrapping them in
`CX_VALUE(...)` means they will get compile-time formatted.
[source,cpp]
----
auto s = stdx::ct_format<"Hello {} {}">(CX_VALUE(42), 17);
// s is stdx::format_result{"Hello 42 {}"_ctst, stdx::tuple{17}}
----

If there are no runtime arguments, the result is a `format_result` with an empty tuple...
[source,cpp]
----
auto s = stdx::ct_format<"Hello {} {}">(CX_VALUE(42), CX_VALUE(17));
// s is stdx::format_result{"Hello 42 17"_ctst, stdx::tuple{}}
----

...and a `format_result` like this without an runtime arguments is implicitly convertible back
to a `ct_string`, or explicitly convertible using unary `operator+`:
[source,cpp]
----
template <stdx::ct_string S> auto f() { ... };

f<stdx::ct_format<"Hello {}">(CX_VALUE(42))>(); // equivalent to f<"Hello 42">()
+stdx::ct_format<"Hello {}">(CX_VALUE(42));     // equivalent to stdx::ct_string{"Hello 42"}
----

NOTE: Using `operator+` on a `format_result` that has a non-empty tuple of
runtime arguments is a compilation error.

Types and compile-time enumeration values are stringified thus:
[source,cpp]
----
enum struct E { value };
auto s = stdx::ct_format<"Hello {} {}">(CX_VALUE(int), CX_VALUE(E::value));
// s is stdx::format_result{"Hello int value"_ctst, stdx::tuple{}}
----

NOTE: Compile-time formatting is done with https://github.com/fmtlib/fmt[fmtlib]
and supports the same formatting DSL. Positional arguments are not supported.

When formatting a compile-time `stdx::format_result`, the strings and argument
tuples are collapsed to a single `stdx::format_result`:

[source,cpp]
----
constexpr static auto a = stdx::ct_format<"The answer is {}">(42);
// a is stdx::format_result{"The answer is {}"_ctst, stdx::tuple{42}}

constexpr static auto q = stdx::ct_format<"{}. But what is the question?">(CX_VALUE(a));
// q is stdx::format_result{"The answer is {}. But what is the question?"_ctst, stdx::tuple{42}}
----
