
== `ct_string.hpp`

A `ct_string` is a compile-time string that can be used as a non-type template
parameter (NTTP).

NOTE: `ct_string` is available only in C++20 and later. It requires compiler
support for https://wg21.link/p0732[using structural types as NTTPs].

Example usage:
[source,cpp]
----
template <ct_string S>
struct named_thing { ... };

auto my_thing = named_thing<"mine">{};
----
Here we declare a `struct` with an NTTP, and instantiate the template with a
string. When compiled, `"mine"` will create a `ct_string` which is the NTTP
passed to `named_thing`.

NOTE: `ct_string` is a class template. The declaration of `named_thing` here
uses `ct_string` as a _placeholder type_ for an NTTP, whose concrete type will
be deduced. This is new for C++20 - see
https://en.cppreference.com/w/cpp/language/template_parameters for details.

The `ct_string` interface:
[source,cpp]
----
template <ct_string S>
struct named_thing {
  template <ct_string Other>
  auto f() {
    // here we can:
    constexpr std::size_t sz = S.size();  // ask for ct_string's size
    constexpr bool is_empty = S.empty();  // ask whether a ct_string is empty
    constexpr bool equal = S == Other;    // compare two ct_strings

    // we can also convert to/from cib string constants
    constexpr auto cib_sc_string = stdx::ct_string_to_type<S, sc::string_constant>();
    constexpr auto stdx_ct_string = stdx::ct_string_from_type(cib_sc_string);
    static_assert(S == stdx_ct_string);

    // we can make a ct_string with a UDL:
    using namespace stdx::ct_string_literals;
    constexpr auto s = "Hello"_cts;

    // we can concatenate two ct_strings:
    constexpr auto s1 = "abc"_cts;
    constexpr auto s2 = "def"_cts;
    constexpr auto s3 = s1 + s2; // abcdef

    // and we can split a ct_string at the first occurrence of a character,
    // optaining a pair of ct_strings
    constexpr auto p = stdx::split<S, '/'>();
    // if the character doesn't exist, p.first is equal to S and p.second is empty
    // otherwise p.first is everything up to (but not including) the character,
    // and p.second is everything after (also not including)

    // we can also iterate over a ct_string
    for (auto c : S) { ... }

    // a ct_string can also explicitly convert to a std::string_view
    constexpr auto sv = static_cast<std::string_view>(S);

    // when required, we can access the underlying array of chars,
    // which includes the null terminator
    const auto& char_array = S.value;
  }
};
----

NOTE: `size` and `empty` are always available as `constexpr`.

NOTE: `_cts` is a user-defined literal declared in
`stdx::literals::ct_string_literals`, where both `literals` and
`ct_string_literals` are inline namespaces.

CAUTION: `ct_string` stores an internal array (`value`) which includes the null
terminator for the string. The `size` reported by the `ct_string` is one less
than the size of the internal array. Thus the `begin`, `end` and `size` of a
`ct_string` all represent the string of characters without the null terminator.
However, for interfacing with legacy functions, a null terminator can be useful.

See https://github.com/intel/compile-time-init-build/tree/main/include/sc[cib
documentation] for details about the cib string constant class.

=== `cts_t`

Sometimes it is useful to wrap a `ct_string` in a type to preserve compile-time
properties. For this, there is `cts_t` and a corresponding user-defined literal.
[source,cpp]
----
using namespace stdx::literals;

constexpr auto s = "hello"_ctst;
// s is a stdx::cts_t<"hello">
----
Think of `cts_t` relating to `ct_string` as `std::integral_constant` relates to `int`.

A `cts_t` is implicitly convertible to a `ct_string`, or can be explicitly
converted with unary `operator+`:


[source,cpp]
----
using namespace stdx::literals;

template <stdx::ct_string S>
constexpr bool always_true = true;

constexpr auto s = "hello"_ctst;
static_assert(always_true<s>);    // implicit conversion
static_assert(always_true<+s>);   // explicit conversion with +
----

=== Named Types

`ct_string.hpp` also contains some functionality that can be used to name types
with a `ct_string`, and detect and retrieve names easily.

==== `with_name`

`with_name` is an empty class template that exposes a `constexpr static` `ct_string`
`name` member. A type named in this way models the `named` concept.

[source,cpp]
----
struct S : stdx::with_name<"name"> {
  // constexpr static auto name = stdx::ct_string{"name"};
};

static_assert(stdx::named<S>);
----

==== `name_of_v` and `constant_name_of_{t,v}`

To retrieve the name of a type, use `name_of_v`. To get it as a `cts_t`, use
`constant_name_of_v` (whose type is `constant_name_of_t`).

[source,cpp]
----
static_assert(stdx::name_of_v<S> == "name"_cts);
static_assert(stdx::constant_name_of_v<S> == "name"_ctst>);
using N = stdx::constant_name_of_t<S>; // stdx::cts_t<"name">
----

==== `name_for` and `constant_name_for`

When you don't know whether or not a type has a name, `name_for` will return
either its name or a `ct_string` of its type. `constant_name_for` will return
the same content as a `cts_t`.

[source,cpp]
----
static_assert(stdx::name_for<S>() == "name"_cts);
static_assert(stdx::name_for<int>() == "int"_cts);

static_assert(stdx::constant_name_for<S>() == "name"_ctst);
static_assert(stdx::constant_name_for<int>() == "int"_ctst);
----

==== `matching_name` and `same_name`

Use the `matching_name` concept to check whether a type's name matches a string.
Use `same_name` to check whether two types are named the same.

[source,cpp]
----
static_assert(stdx::matching_name<S, "name">);
static_assert(stdx::same_name<S, stdx::with_name<"name">>);
----

`matching_name` and `same_name` have corresponding
https://cppreference.com/cpp/types/integral_constant[`std::bool_constant`] types
and
https://www.boost.org/doc/libs/latest/libs/mp11/doc/html/mp11.html#definitions[quoted
metafunctions] for metaprogramming use.

[source,cpp]
----
// _t indicates a std::bool_constant of the concept
static_assert(stdx::matching_name_t<S, "name">::value);
static_assert(stdx::same_name_t<S, stdx::with_name<"name">>::value);

// _q indicates a quoted metafunction that exposes fn (returning a std::bool_constant)
static_assert(stdx::matching_name_q<"name">::template fn<S>::value);
static_assert(stdx::same_name_q<stdx::with_name<"name">>::template fn<S>::value);
----

==== Formatted names

Because a `ct_string` can be implicitly constructed from the result of a fully
compile-time invocation of `STDX_CT_FORMAT`, types can be named by formatting:

[source,cpp]
----
auto suffix = "name"_ctst;
struct S : stdx::with_name<STDX_CT_FORMAT("S {}", suffix)> {};
----
