
== `utility.hpp`

=== `as_unsigned` and `as_signed`

`as_unsigned` and `as_signed` are useful functions for converting integral types
to their opposite-signed type. Under the hood, it's a `static_cast` to the
appropriate
https://en.cppreference.com/w/cpp/types/make_unsigned[`std::make_unsigned_t`] or
https://en.cppreference.com/w/cpp/types/make_signed[`std::make_signed_t`].

[source,cpp]
----
auto x = 1729;                 // int
auto y = stdx::as_unsigned(x); // unsigned int
----

=== `CX_VALUE`

`CX_VALUE` is a macro that wraps its argument in a constexpr callable, which can
be used as a
https://en.cppreference.com/w/cpp/language/template_parameters#Non-type_template_parameter[non-type
template argument]. The compile-time value can be retrieved by calling the
callable. This is useful for passing non-structural types as template arguments.

[source,cpp]
----
// A std::string_view value cannot be a template argument,
// so wrap it in CX_VALUE
constexpr auto ts_value = CX_VALUE(std::string_view{});
auto o = stdx::optional<std:string_view,
                        stdx::tombstone_value<ts_value>>;
----

NOTE: This is supported for C++20 and later: it still requires the ability to
pass lambda expressions as non-type template arguments. The type must still be a
https://en.cppreference.com/w/cpp/named_req/LiteralType[literal type] to be used
at compile time, but need not necessarily be a structural type. (The usual
difference is that structural types cannot have private members.)

=== `forward_like`

`forward_like` is an implementation of
https://en.cppreference.com/w/cpp/utility/forward_like[`std::forward_like`].
`forward_like_t` is also provided.

[source,cpp]
----
static_assert(stdx::same_as<stdx::forward_like_t<int &, float>, float &>);
----

=== `FWD`

`FWD` is a macro that perfectly forwards its argument. It's useful for C++17
lambdas which can't have a template head to name their types.

[source,cpp]
----
// C++20 and later possibility
auto l = [] <typename Arg> (auto&& arg) {
  return f(std::forward<Arg>(arg));
};

// equivalent
auto l = [] (auto&& arg) {
  return f(FWD(arg));
};
----

=== `overload`

`overload` is a struct designed to encapsulate an overload set. It inherits from
all the lambda expressions used to construct it. As an example, it's useful for
visiting a variant.

[source,cpp]
----
auto f(std::variant<int, float, std::string> const& v) {
  return std::visit(
    stdx::overload{
      [] (std::string const& s) { return s; },
      [] (auto num) { return std::to_string(num); }
    }, v);
}
----

=== `sized`

`sized` offers an easy way to convert array extents between arrays of different
integral types.

How many times have you written something like this?
[source,cpp]
----
// I have N bytes, and I need to compute the number of uint32_ts to store them
const auto dword_size = (N + sizeof(std::uint32_t) - 1) / sizeof(std::uint32_t);
----

Or perhaps more likely and less portably:
[source,cpp]
----
const auto dword_size = (N + 3) / 4;
----

`sized` allows this conversion to be safer, more expressive, and more portable.
[source,cpp]
----
// I have N bytes, and I need to compute the number of uint32_ts to store them
const auto dword_size = stdx::sized8{N}.in<std::uint32_t>();

// I have M std::uint16_ts, and I need to compute the number of uint64_ts to store them
const auto qword_size = stdx::sized16{M}.in<std::uint64_t>();

// generally, I have K things of type T, I need to compute the number of Us to store them
const auto sz = stdx::sized<T>{K}.template in<U>();
----

- `sized8` is an alias for `sized<std::uint8_t>`
- `sized16` is an alias for `sized<std::uint16_t>`
- `sized32` is an alias for `sized<std::uint32_t>`
- `sized64` is an alias for `sized<std::uint64_t>`

The `sized` conversion works either from larger type to smaller type, or the
other way around. Or even where the source and destination types are the same.

=== `type_map`

`type_map` is a structure designed to allow compile-time lookups of types or
values. The basic idea is having a "map" of key-value pairs. Each key-value is a
`type_pair`, and all the `type_pair`​s form a map. Values in the map can be
looked up using `type_lookup_t`.

[source,cpp]
----
// A, B, C, X, and Y are types - they don't have to be complete
using M = stdx::type_map<stdx::type_pair<A, X>, stdx::type_pair<B, Y>>;
using T = stdx::type_lookup_t<M, A>; // X
using U = stdx::type_lookup_t<M, B>; // Y
using Z = stdx::type_lookup_t<M, C>; // void, because C is not in the map
----

`type_lookup_t` takes an optional third argument to be returned as the default
(`void` above). The most common use case is for `type_map` to holds types, but
there are convenience aliases for dealing with compile-time values in each of
the four possibilities:

- `type_lookup_t` - for mapping from types to types
- `type_lookup_v` - for mapping from types to values
- `value_lookup_t` - for mapping from values to types
- `value_lookup_v` - for mapping from values to values

And `type_pair` has corresponding aliases to make the appropriate `type_map`​s:

- `tt_pair` - for type-type maps
- `tv_pair` - for type-value maps
- `vt_pair` - for value-type maps
- `vv_pair` - for value-value maps

[source,cpp]
----
// a type-type map that uses type_lookup_t
using M1 = stdx::type_map<stdx::tt_pair<A, X>, stdx::tt_pair<B, Y>>;
using T1 = stdx::type_lookup_t<M1, A>; // X

// a type-value map that uses type_lookup_v
using M2 = stdx::type_map<stdx::tv_pair<A, 0>, stdx::tv_pair<B, 1>>;
constexpr auto v2 = stdx::type_lookup_v<M2, A>; // 0

// a value-type map that uses value_lookup_t
using M3 = stdx::type_map<stdx::vt_pair<0, X>, stdx::vt_pair<1, Y>>;
using T3 = stdx::value_lookup_t<M3, 0>; // X

// a value-value map that uses value_lookup_v
using M4 = stdx::type_map<stdx::vv_pair<0, 42>, stdx::vv_pair<1, 17>>;
constexpr auto v4 = stdx::value_lookup_v<M4, 0>; // 42
----

In the case of mapping to types, the `*_lookup_t` aliases have optional third
type arguments which are defaults returned when lookup fails. In the case of
mapping to values, the `*_lookup_v` aliases have optional third NTTP arguments
in the same role.

=== `unreachable`

`unreachable` is an implementation of
https://en.cppreference.com/w/cpp/utility/unreachable[`std::unreachable`].

[source,cpp]
----
[[noreturn]] inline auto unreachable() -> void {
  // if this function is ever called, it's
  // undefined behaviour
}
----
