name: Usage Test
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  USER_LLVM_VERSION: 14
  USER_CMAKE_VERSION: 3.25

jobs:
  usage_test:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cpp_implementation: [FREESTANDING, HOSTED]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install compiler
        run: sudo apt update && sudo apt-get install -y clang-${{env.USER_LLVM_VERSION}}

      - name: Install cmake
        run: |
          pip3 install --upgrade pip
          pip3 install --force cmake==${{env.USER_CMAKE_VERSION}}

      - name: Configure CMake
        working-directory: ${{github.workspace}}/usage_test
        env:
          CC: "/usr/lib/llvm-${{env.USER_LLVM_VERSION}}/bin/clang"
          CXX: "/usr/lib/llvm-${{env.USER_LLVM_VERSION}}/bin/clang++"
        run: ~/.local/bin/cmake -B build -DCPP_IMPLEMENTATION=${{matrix.cpp_implementation}}

      - name: Build
        working-directory: ${{github.workspace}}/usage_test
        run: ~/.local/bin/cmake --build build
